SELECT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE * 30 - A.DAILY_FEE * 30 * 0.01 * B.DISCOUNT_RATE) FEE
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
    ON A.CAR_TYPE = B.CAR_TYPE
WHERE A.CAR_ID NOT IN (SELECT DISTINCT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE (TO_CHAR(START_DATE, 'YYYYMM') <= '202211' AND
                     TO_CHAR(END_DATE, 'YYYYMM') >= '202211'))
    AND A.CAR_TYPE IN ('SUV', '세단')
    AND B.DURATION_TYPE = '30일 이상'
    AND ROUND(A.DAILY_FEE * 30 - A.DAILY_FEE * 30 * 0.01 * B.DISCOUNT_RATE) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;