SELECT MONTH
     , CAR_ID
     , RECORDS
  FROM (
      SELECT DISTINCT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS MONTH
           , CAR_ID
           , COUNT(*) OVER(PARTITION BY TO_CHAR(START_DATE, 'MM'), CAR_ID) AS RECORDS
           , COUNT(*) OVER(PARTITION BY CAR_ID) AS FILTER
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
       WHERE TO_CHAR(START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210'
  )
 WHERE FILTER >= 5
 ORDER BY MONTH, CAR_ID DESC