WITH TEMP AS
(
    SELECT ROWNUM - 1 AS HOUR
      FROM DUAL
   CONNECT BY ROWNUM <= 24
)
SELECT T.HOUR
     , COUNT(A.ANIMAL_ID) AS CNT
  FROM TEMP T
  LEFT OUTER JOIN ANIMAL_OUTS A
    ON T.HOUR = TO_CHAR(A.DATETIME, 'HH24')
 GROUP BY T.HOUR
 ORDER BY T.HOUR