SELECT MAX(CATEGORY) KEEP(DENSE_RANK FIRST ORDER BY PRICE DESC) AS CATEGORY
     , MAX(PRICE) AS MAX_PRICE
     , MAX(PRODUCT_NAME) KEEP(DENSE_RANK FIRST ORDER BY PRICE DESC) AS PRODUCT_NAME
  FROM FOOD_PRODUCT
 WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
 GROUP BY CATEGORY
 ORDER BY MAX_PRICE DESC