WITH TEMP AS (
    SELECT A.MEMBER_ID
         , MAX(A.MEMBER_NAME) AS MEMBER_NAME
         , COUNT(A.MEMBER_ID) AS COUNT
      FROM MEMBER_PROFILE A
     INNER JOIN REST_REVIEW B
        ON A.MEMBER_ID = B.MEMBER_ID
     GROUP BY A.MEMBER_ID
)
SELECT A.MEMBER_NAME
     , B.REVIEW_TEXT
     , TO_CHAR(B.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
  FROM TEMP A
  LEFT OUTER JOIN REST_REVIEW B
    ON A.MEMBER_ID = B.MEMBER_ID
 WHERE A.COUNT = (SELECT MAX(COUNT) FROM TEMP)
 ORDER BY REVIEW_DATE, B.REVIEW_TEXT