SELECT MAX(A.AUTHOR_ID) AS AUTHOR_ID
     , MAX(B.AUTHOR_NAME) AS AUTHOR_NAME
     , MAX(A.CATEGORY) AS CATEGORY
     , SUM(A.PRICE * C.SALES) AS TOTAL_SALES
  FROM BOOK A
 INNER JOIN AUTHOR B
    ON A.AUTHOR_ID = B.AUTHOR_ID
 INNER JOIN BOOK_SALES C
    ON A.BOOK_ID = C.BOOK_ID
 WHERE TO_CHAR(C.SALES_DATE, 'YYYYMM') = '202201'
 GROUP BY A.AUTHOR_ID, A.CATEGORY
 ORDER BY AUTHOR_ID, CATEGORY DESC