WITH TEMP AS (
    SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE '20221016' BETWEEN TO_CHAR(START_DATE, 'YYYYMMDD') AND TO_CHAR(END_DATE, 'YYYYMMDD')
)
SELECT DISTINCT A.CAR_ID
     , CASE WHEN B.CAR_ID IS NULL THEN '대여 가능' ELSE '대여중' END AS AVAILABILITY
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
  LEFT OUTER JOIN TEMP B
    ON A.CAR_ID = B.CAR_ID
 ORDER BY A.CAR_ID DESC