SELECT CASE WHEN HOUR LIKE '0%' THEN '9' ELSE HOUR END
     , COUNT(*) AS COUNT
  FROM (
      SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR
        FROM ANIMAL_OUTS
       WHERE TO_CHAR(DATETIME, 'HH24') >= '09'
         AND TO_CHAR(DATETIME, 'HH24') <= '19'
  )
 GROUP BY HOUR
 ORDER BY HOUR