SELECT RI.REST_ID
     , MAX(RI.REST_NAME) AS REST_NAME
     , MAX(RI.FOOD_TYPE) AS FOOD_TYPE
     , MAX(RI.FAVORITES) AS FAVORITES
     , MAX(RI.ADDRESS) AS ADDRESS
     , ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE
  FROM REST_INFO RI
 INNER JOIN REST_REVIEW RR
    ON RI.REST_ID = RR.REST_ID
 WHERE RI.ADDRESS LIKE '서울%'
 GROUP BY RI.REST_ID
 ORDER BY SCORE DESC, FAVORITES DESC